import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { Order } from "@/types/order";

export function generatePDF(order: Order) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFillColor(30, 58, 95);
  doc.rect(0, 0, pageWidth, 35, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("ORDER BOOK", pageWidth / 2, 15, { align: "center" });
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Professional Order Management", pageWidth / 2, 22, { align: "center" });

  // Customer Info
  doc.setFontSize(9);
  doc.text(`Date: ${order.date}`, pageWidth - 15, 30, { align: "right" });

  let y = 42;
  doc.setTextColor(30, 58, 95);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Customer Details", 15, y);
  y += 6;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(60, 60, 60);
  if (order.customerName) { doc.text(`Name: ${order.customerName}`, 15, y); y += 5; }
  if (order.address) { doc.text(`Address: ${order.address}`, 15, y); y += 5; }
  if (order.phone) { doc.text(`Phone: ${order.phone}`, 15, y); y += 5; }

  // Summary bar
  y += 3;
  doc.setFillColor(240, 245, 255);
  doc.roundedRect(15, y, pageWidth - 30, 12, 2, 2, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(30, 58, 95);
  doc.text(`Total Items: ${order.totalItems}`, 20, y + 8);
  doc.text(`Gross Qty: ${order.totalQuantity}`, pageWidth / 2 - 15, y + 8);
  if (order.totalValue > 0) {
    doc.text(`Value: ₹${order.totalValue.toLocaleString("en-IN")}`, pageWidth - 20, y + 8, { align: "right" });
  }
  y += 18;

  // Group items by category
  const grouped: Record<string, typeof order.items> = {};
  order.items.forEach((item) => {
    if (!grouped[item.category]) grouped[item.category] = [];
    grouped[item.category].push(item);
  });

  Object.entries(grouped).forEach(([category, items]) => {
    // Category header
    doc.setFillColor(30, 58, 95);
    doc.rect(15, y, pageWidth - 30, 7, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.text(category, 18, y + 5);
    y += 8;

    const hasRates = items.some((i) => i.rate > 0);
    const headers = hasRates
      ? [["#", "Item", "Qty", "Unit", "Rate (₹)", "Amount (₹)"]]
      : [["#", "Item", "Qty", "Unit"]];

    const body = items.map((item, idx) => {
      const row = [(idx + 1).toString(), item.productName, item.quantity.toString(), item.unit];
      if (hasRates) {
        row.push(item.rate > 0 ? item.rate.toString() : "-");
        row.push(item.rate > 0 ? (item.quantity * item.rate).toString() : "-");
      }
      return row;
    });

    autoTable(doc, {
      startY: y,
      head: headers,
      body: body,
      margin: { left: 15, right: 15 },
      theme: "grid",
      headStyles: {
        fillColor: [220, 230, 245],
        textColor: [30, 58, 95],
        fontStyle: "bold",
        fontSize: 8,
      },
      bodyStyles: {
        fontSize: 8,
        textColor: [50, 50, 50],
      },
      alternateRowStyles: {
        fillColor: [248, 250, 255],
      },
      columnStyles: hasRates
        ? { 0: { cellWidth: 10 }, 2: { halign: "center" }, 3: { halign: "center" }, 4: { halign: "right" }, 5: { halign: "right" } }
        : { 0: { cellWidth: 10 }, 2: { halign: "center" }, 3: { halign: "center" } },
    });

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    y = ((doc as any).lastAutoTable?.finalY || y + 15) + 5;
  });

  // Notes
  if (order.notes) {
    y += 3;
    if (y > 260) { doc.addPage(); y = 15; }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(30, 58, 95);
    doc.text("Notes / Message:", 15, y);
    y += 5;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(60, 60, 60);
    const lines = doc.splitTextToSize(order.notes, pageWidth - 30);
    doc.text(lines, 15, y);
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by Order Book", pageWidth / 2, doc.internal.pageSize.getHeight() - 8, { align: "center" });
  }

  doc.save(`Order_${order.customerName || "Unknown"}_${order.date.replace(/\//g, "-")}.pdf`);
}
